# Copyright (C) 2013-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Check if EPEL repo is already configured.
  stat:
    path: "/etc/yum.repos.d/epel.repo"
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Check if Nux-Desktop repo is already configured.
  stat:
    path: "/etc/yum.repos.d/nux-dextop.repo"
  register: nux_repofile_result

- name: Install Nux-Desktop repo.
  yum:
    name: "http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el{{ ansible_distribution_major_version }}.nux.noarch.rpm"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not nux_repofile_result.stat.exists

- name: Import Nux-Desktop GPG key.
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-nux.ro"
    state: present
  when: not nux_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install default packages
  yum:
    name: {{ item }}
    state: present
  with_items:
    - openssh
    - wget
    - curl
    - net-tools
    - ngrep
    - tree
    - git
    - gnupg
    - tig
    - unzip
    - rsyslog
    - tmux

- name: Install X
  yum:
    name: {{ item }}
    state: present
  with_items:
    - xorg-x11-server-Xorg
    - xorg-x11-xinit
    - xterm
    - terminus-fonts
    - lightdm
