# Copyright (C) 2013-2018 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Install EPEL Repository
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - epel-release

- name: Enable Nux-Desktop repository
  yum_repository:
    name: nux-dextop
    description: Nux.Ro RPMs for general desktop use
    baseurl: http://li.nux.ro/download/nux/dextop/el{{ ansible_distribution_major_version }}/$basearch/ http://mirror.li.nux.ro/li.nux.ro/nux/dextop/el{{ ansible_distribution_major_version }}/$basearch/
    gpgkey: http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
    gpgcheck: true
    skip_if_unavailable: true

- name: Enable Repoforge repository
  yum_repository:
    name: rpmforge
    description: RPMforge YUM repo
    file: external_repos
    baseurl: http://apt.sw.be/redhat/el{{ ansible_distribution_major_version }}/en/$basearch/rpmforge
    mirrorlist: http://mirrorlist.repoforge.org/el{{ ansible_distribution_major_version }}/mirrors-rpmforge
    enabled: true

- name: Install shell tools
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - tmux
      - tree
      - ncdu

- name: Install default packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ngrep
      - git
      - gnupg2
      - tig
      - unzip
      - rsyslog

- name: Install terminal emulators
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - terminator

- name: Install network tools
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - openssh
      - wget
      - curl
      - net-tools
      - mtr
      - traceroute
      - nmap
      - ngrep
      - nethogs
